### ISSUE TITLE
ChatRoomListAdapter.java 파일에 클래스 두 개 있는 문제.

### ISSUE THREAD

**Issue by wph144** [yundaeun/messageChatHead#2]
아까 ChatBubbleCreator.java 파일에 클래스 두 개 있던 문제랑 똑같이 inner class가 바깥에 잘못 나와 있어서 그런거네요. 수정해주세요~

추가로.. 따로 이슈 만들기 애매해서 여기에 씁니다. 
adapter 패키지 쪽에 들여쓰기와 { } 스타일 맞춰주세요 ^^

**Comment by yundaeun** [comment]
네 수정했습니다!
