### ISSUE TITLE
layoutInflater 멤버변수

### ISSUE THREAD

**Issue by wph144** [yundaeun/messageChatHead#4]
변수는 scope이 작을 수록 좋은데 layoutInflater가 멤버변수로 있습니다

-보통 inflate를 여기저기서 하지 않고 몰아서 하기 때문에 지역변수로 괜찮을 것 같습니다
-변수 따로 만들지 않고 View.inflate 사용해도 대부분 됩니다. View의 스태틱메서드이기 때문에 혹시 inflate하는 곳이 View 안이라면 그냥 아래처럼 inflate 써도 됩니다. 
chatView = inflate(getContext(), R.layout.chat_view_layout, null);

참고.. http://uroa.tistory.com/3

**Comment by yundaeun** [comment]
수정했습니다~
