### ISSUE TITLE
터치 업 시 왼쪽 끝이나 오른쪽 끝으로 이동

### ISSUE THREAD

**Issue by wph144** [yundaeun/messageChatHead#6]
왼편에 있는지 오른편에 있는지 판단해서 이동시키기 (일단 애니메이션 없이)

**Comment by yundaeun** [comment]
완료했습니다

오른쪽에서 왼쪽으로 이동 시,
느리게 따라오는 현상이 나타남.. (왼쪽에서 오른쪽 이동은 문제 없음.)

**Comment by wph144** [comment]
if (faceIconParams.x > ChatBubbleHelper.displayWidth / 2) {
                    faceIconParams.x = ChatBubbleHelper.displayWidth \* 4/5;
                } else {
                    faceIconParams.x = 0;
                }

이 부분은 메서드 추출하는게 좋을것 같아요. isLeftSide(), goToLeft(), goToRight() 정도로 만들면 읽기 좋을 것 같네요.

**Comment by yundaeun** [comment]
수정 후 푸시했습니다!

**Comment by wph144** [comment]
moveToLeft 가 더 좋네요. 수고했어요~
